DROP TABLE IF EXISTS `dog` CASCADE;

CREATE TABLE `dog` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`breed` VARCHAR(255) NOT NULL,
	`friendly` VARCHAR(255) NOT NULL,
	`fee` DOUBLE NOT NULL);